//
//  RegisterWorker.swift
//  Mobe
//
//  Created by Igor Soares on 22/09/19.
//  Copyright (c) 2019 Igor Soares. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class RegisterWorker
{
  func doSomeWork()
  {
  }
}
