//
//  RegisterPresenter.swift
//  Mobe
//
//  Created by Igor Soares on 22/09/19.
//  Copyright (c) 2019 Igor Soares. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegisterPresentationLogic
{
  func presentSomething(response: Register.Something.Response)
}

class RegisterPresenter: RegisterPresentationLogic
{
  weak var viewController: RegisterDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Register.Something.Response)
  {
    
    var viewModel = Register.Something.ViewModel(titleMessage: "", message: "")

    if let error = response.error {
      viewModel = Register.Something.ViewModel(titleMessage: "Que pena!", message: error)
    } else {
      viewModel = Register.Something.ViewModel(titleMessage: "Parabéns", message: "Seu cadastro foi concluído com sucesso!")
    }
    
    viewController?.displaySomething(viewModel: viewModel)
  }
}
